name: tensorflow
channels:
  - menpo
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - bcolz=1.2.1=py36h04863e7_0
  - bleach=1.5.0=py36_0
  - blosc=1.14.4=hdbcaa40_0
  - bokeh=0.13.0=py36_0
  - click=6.7=py36_0
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.1.2=cuda9.0_0
  - cupti=9.0.176=0
  - cytoolz=0.9.0.1=py36h14c3975_1
  - dask=0.18.2=py36_0
  - distributed=1.22.1=py36_0
  - expat=2.2.6=he6710b0_0
  - flask=1.0.2=py36_1
  - glib=2.56.2=hd408876_0
  - heapdict=1.0.0=py36_2
  - html5lib=0.9999999=py36_0
  - itsdangerous=1.1.0=py36_0
  - jinja2=2.10=py36_0
  - keras-gpu=2.2.2=0
  - libpng=1.6.36=hbc83047_0
  - locket=0.2.0=py36_1
  - lzo=2.10=h49e0be7_2
  - msgpack-python=0.5.6=py36h6bb024c_1
  - numexpr=2.6.7=py36h00253c6_0
  - numpy=1.15.4=py36h1d66e8a_0
  - numpy-base=1.15.4=py36h81de0dd_0
  - packaging=17.1=py36_0
  - pandas=0.23.4=py36h04863e7_0
  - partd=0.3.8=py36_0
  - patsy=0.5.0=py36_0
  - psutil=5.4.6=py36h14c3975_0
  - pyqt=5.9.2=py36h05f1152_2
  - pytables=3.4.4=py36ha205bf6_0
  - python=3.6.8=h0371630_0
  - qt=5.9.7=h5867ecd_1
  - scikit-learn=0.19.1=py36hedc7406_0
  - seaborn=0.9.0=py36_0
  - snappy=1.1.7=hbae5bb6_3
  - sortedcontainers=2.0.4=py36_0
  - sqlite=3.26.0=h7b6447c_0
  - statsmodels=0.9.0=py36h035aef0_0
  - tblib=1.3.2=py36_0
  - tensorflow-gpu=1.5.0=0
  - tensorflow-gpu-base=1.5.0=py36h8a131e3_0
  - tensorflow-tensorboard=1.5.1=py36hf484d3e_1
  - tk=8.6.8=hbc83047_0
  - zict=0.1.3=py36_0
  - ca-certificates=2018.11.29=ha4d7672_0
  - certifi=2018.11.29=py36_1000
  - gnutls=3.5.19=h2a4e5f8_1
  - imagehash=4.0=py_0
  - keras=2.2.2=py36_0
  - nettle=3.3=0
  - openh264=1.7.0=0
  - openssl=1.1.1a=h14c3975_1000
  - tensorflow=1.9.0=py36_0
  - x264=1!152.20180717=h470a237_0
  - xgboost=0.72.1=py36hfc679d8_1
  - xorg-kbproto=1.0.7=h470a237_2
  - xorg-libice=1.0.9=h470a237_4
  - xorg-libsm=1.2.2=h470a237_5
  - xorg-libx11=1.6.5=h470a237_2
  - xorg-libxext=1.3.3=h470a237_4
  - xorg-libxrender=0.9.10=h470a237_2
  - xorg-renderproto=0.11.1=h470a237_2
  - xorg-xextproto=7.3.0=h470a237_2
  - xorg-xproto=7.0.31=h470a237_7
  - _tflow_190_select=0.0.3=mkl
  - absl-py=0.3.0=py36_0
  - astor=0.7.1=py36_0
  - backcall=0.1.0=py36_0
  - binutils_impl_linux-64=2.28.1=had2808c_3
  - binutils_linux-64=7.2.0=had2808c_27
  - blas=1.0=mkl
  - bzip2=1.0.6=h14c3975_5
  - cairo=1.14.12=h8948797_3
  - cloudpickle=0.5.3=py36_0
  - cycler=0.10.0=py36_0
  - cython=0.28.5=py36hf484d3e_0
  - dask-core=0.18.2=py36_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - ffmpeg=3.4=h7985aa0_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_0
  - gast=0.2.0=py36_0
  - gcc_impl_linux-64=7.2.0=habb00fd_3
  - gcc_linux-64=7.2.0=h550dcbe_27
  - gettext=0.19.8.1=hd7bead4_3
  - giflib=5.1.4=h14c3975_1
  - gmp=6.1.2=h6c8ec71_1
  - graphite2=1.3.11=h16798f4_2
  - grpcio=1.12.1=py36hdbcaa40_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gxx_impl_linux-64=7.2.0=hdf63c60_3
  - gxx_linux-64=7.2.0=h550dcbe_27
  - h5py=2.8.0=py36h8d01980_0
  - harfbuzz=1.8.4=hec2c2bc_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - imageio=2.3.0=py36_0
  - intel-openmp=2018.0.3=0
  - ipykernel=4.8.2=py36_0
  - ipython=6.5.0=py36_0
  - ipython_genutils=0.2.0=py36_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.12.1=py36_0
  - jpeg=9b=h024ee3a_2
  - jupyter_client=5.2.3=py36_0
  - jupyter_core=4.4.0=py36_0
  - keras-applications=1.0.4=py36_0
  - keras-base=2.2.2=py36_0
  - keras-preprocessing=1.0.2=py36_0
  - kiwisolver=1.0.1=py36hf484d3e_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libglu=9.0.0=hf484d3e_1
  - libgpuarray=0.7.6=h14c3975_0
  - libiconv=1.15=h63c8f33_5
  - libopenblas=0.2.20=h9ac9557_7
  - libopencv=3.4.1=h8fa1ad8_3
  - libopus=1.2.1=hb9ed12e_0
  - libprotobuf=3.5.2=h6f1eeef_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_1
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.0.0=h222930b_1
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - mako=1.0.7=py36_0
  - markdown=2.6.11=py36_0
  - markupsafe=1.0=py36h14c3975_1
  - matplotlib=2.2.3=py36hb69df0a_0
  - mkl=2018.0.3=1
  - mkl-service=1.1.2=py36h651fb7a_4
  - mkl_fft=1.0.4=py36h4414c95_1
  - mkl_random=1.0.1=py36h4414c95_1
  - ncurses=6.1=hf484d3e_0
  - networkx=2.1=py36_0
  - olefile=0.45.1=py36_0
  - openblas=0.2.20=4
  - openblas-devel=0.2.20=7
  - opencv=3.4.1=py36h6fd60c2_3
  - parso=0.3.1=py36_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pillow=5.2.0=py36heded4f4_0
  - pip=10.0.1=py36_0
  - pixman=0.34.0=hceecf20_3
  - prompt_toolkit=1.0.15=py36_0
  - protobuf=3.5.2=py36hf484d3e_1
  - ptyprocess=0.6.0=py36_0
  - py-opencv=3.4.1=py36h8fa1ad8_3
  - pygments=2.2.0=py36_0
  - pygpu=0.7.6=py36h035aef0_0
  - pyparsing=2.2.0=py36_1
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - pywavelets=0.5.2=py36h035aef0_2
  - pyyaml=3.13=py36h14c3975_0
  - pyzmq=17.1.2=py36h14c3975_0
  - readline=7.0=ha6073c6_4
  - scikit-image=0.14.0=py36hf484d3e_1
  - scipy=1.1.0=py36hc49cb51_0
  - setuptools=40.0.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36hf484d3e_0
  - six=1.11.0=py36_1
  - tensorboard=1.9.0=py36hf484d3e_0
  - tensorflow-base=1.9.0=mkl_py36h2ca6a6a_0
  - termcolor=1.1.0=py36_1
  - theano=1.0.2=py36h6bb024c_0
  - toolz=0.9.0=py36_0
  - tornado=5.1=py36h14c3975_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.5=hf484d3e_0
  - zlib=1.2.11=ha838bed_2
  - opencv3=3.1.0=py36_0

